# Generated by Django 5.2.8 on 2025-11-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField(max_length=255)),
                ('reserve', models.CharField()),
                ('picture', models.CharField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
