# Generated by Django 5.2.8 on 2025-11-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildLife1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='animals',
            name='picture',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='animals',
            name='reserve',
            field=models.CharField(max_length=255),
        ),
    ]
